#!/bin/bash
# Copyright (c) 2021 Veritas Technologies LLC. All rights reserved. IP63-2828-7171-04-15-9

myprg=$0
myDir=$(dirname ${myprg})

echo "Rolling back the update..."
# NOTE: 
#   1. The rollback plugins would now be called as part of the `asum install`
#       itself.
#   2. This `rollback` script (i.e., ${myprg}) would be called through rollback
#       REST API soon to do rollback-precheck, reboot & then rollback. Till
#       then, this is just a noop i.e., exit with 0.

 ${myDir}/sum rollback "$@"
 if [ $? -ne 0 ]; then
     echo "Error: Failed to roll back the update."
     exit 1
 fi

echo "Successfully rolled back the update."
exit 0
